version: '3.3'

services:
  web:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0